### PR TITLE
update ASM configure for ARM64

### PR DESCRIPTION
**Pull request by bureddy**
- port from ompi/opal_cconfig_asm.m4
        - Fix align header include
        - Add arm64 atomics

### CODE REVIEW

**Comment by miked-mellanox** [comment]
@bureddy - is it in sync w/ ompi ocoms code?

**Comment by bureddy** [comment]
@miked-mellanox you mean OMPI OPAL code?

**Comment by miked-mellanox** [comment]
@bureddy - yep

**Comment by miked-mellanox** [comment]
maybe worth checking if there are some fixes in upstream that are relevant for us.

**Comment by bureddy** [comment]
@miked-mellanox Sure. Will do that in a separate PR.

**Comment by miked-mellanox** [comment]
@shamisp

**Comment by shamisp** [comment]
looks up to date for me (has some of my latest fixes)

**Pull request merged**
